#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/

###

POST http://localhost:3333/busao
Content-Type: application/json

{
    "name": "RV",
    "linha": "112",
    "Terminal": "TICAN",
    "Av": "Presidente Vargas",
    
}

###

PUT http://localhost:3333/users/id
Content-Type: application/json

{
    "name": "RV",
    "linha": "112",
    "Terminal": "TICAN",
    "Av": "Presidente Vargas",

}

###

DELETE http://localhost:3333/users/id
